function y = filter_1(x)
    %FILTER Filters input x and returns output y.
    
    % MATLAB Code
    % Generated by MATLAB(R) 8.6 and the DSP System Toolbox 9.1.
    % Generated on: 11-Feb-2016 17:19:37
    
    %#codegen
    
    % To generate C/C++ code from this function use the codegen command.
    % Type 'help codegen' for more information.
    
    persistent Hd;
    
    if isempty(Hd)
        
        % FIR maximally flat Lowpass filter designed using the MAXFLAT function.
        
        % All frequency values are normalized to 1.
        
        N  = 20;   % Order
        Fc = 0.5;  % Cutoff Frequency
        
        %% Calculate the second-order sections coefficients to avoid round-off
        %errors.
        [b,a,b1,b2,sos_var,g] = maxflat(N, 'sym', Fc);
        Hd = dsp.BiquadFilter( ...
            'Structure', 'Direct form II', ...
            'SOSMatrix', sos_var, ...
            'ScaleValues', g);
    end
    
    y = step(Hd,x);
    
    
    % [EOF]
