function Hd = filter_2
%FILTER_2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the DSP System Toolbox 9.1.
% Generated on: 11-Feb-2016 17:20:20

% FIR maximally flat Lowpass filter designed using the MAXFLAT function.

% All frequency values are normalized to 1.

N  = 20;   % Order
Fc = 0.5;  % Cutoff Frequency

%% Calculate the second-order sections coefficients to avoid round-off
%errors.
[b,a,b1,b2,sos_var,g] = maxflat(N, 'sym', Fc);
Hd                    = dfilt.df2sos(sos_var, g);

% [EOF]
