function tex=tab_param(names,varargin)
    % create a tex table of the parameters
    
    paramvalues=varargin;
    paramnames=cellfun(@inputname,num2cell(2:nargin),'UniformOutput',false);
    header=sprintf([...
        '\\begin{table}\n'...
        '	\\centering\n'...
        '	\\begin{tabular}{%s}\n'...
        '		\\hline\n'...
        '        & %s\\\\\n'...
        '		\\hline\n'...
        ],...
        repmat('l',[1,1+numel(names)]),...
        strjoin(names,' & ')...
        );
    content='';
    for n=1:nargin-1
        content=sprintf('%s		%s & %s\\\\\n',...
            content, ...
            paramnames{n},...
            strjoin(arrayfun(@(x)sprintf('%g',x),paramvalues{n},'UniformOutput',false),' & ')...
            );
    end
    footer=sprintf([...
        '        \\hline\n'...
        '	\\end{tabular}\n'...
        '\\end{table}\n'...
        ]);
    tex=sprintf('%s%s%s',header,content,footer);
end