function outVec = PointInTetrahedron(v1, v2, v3, v4, p)
outVec = [SameSide(v1, v2, v3, v4, p),...
    SameSide(v2, v3, v4, v1, p),...
    SameSide(v3, v4, v1, v2, p),...
    SameSide(v4, v1, v2, v3, p)];
